spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show_sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/discordbot?createDatabaseIfNotExist=true
    username: root
    password: password
    hikari:
      max-lifetime: 580000

tokens:
  file: ${TOKEN_LOCATION:tokens.properties}
web3j:
  client-address: https://arb1.arbitrum.io/rpc