spring:
  jpa:
    hibernate:
      ddl-auto: update
  #    show_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:""}


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/donkeybot?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: password
    hikari:
      max-lifetime: 580000

discord-enabled: true

tokens:
  file: ${TOKEN_LOCATION:tokens.properties}
web3j:
  client-address: https://arb1.arbitrum.io/rpc